version: "3.9"

services:
  db:
    image: postgres:17.5
    restart: always
    container_name: shield_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shield_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  test-db:
    image: postgres:17.5
    container_name: shield_postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shield_test_db
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data # ephemeral

  redis:
    image: redis:8.0.1
    restart: always
    container_name: shield_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
